// Exports: a course or material as Markdown files (zipped with its images),
// and everything in data/ as one zip.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import yazl from "yazl";
import type { Material, MaterialSummary } from "../shared/api";
import {
  ANNOTATED_IMAGE,
  buildOutline,
  contentText,
  DRAWING,
  MATH_BLOCK,
  parseAnnotations,
  walkBlocks,
  type LooseBlock,
  type MentionProps,
} from "../shared/content";
import { asFolder, asImagePage, asNotebook, type MimeBundle, type NotebookContent } from "../shared/pages";
import { writeSnapshot } from "./backup";
import { DATA_DIR, UPLOAD_DIR } from "./db";
import * as repo from "./repo";

// ── Zip assembly ─────────────────────────────────────────────────────────

/** Files of one export, by path inside the zip. */
class Bundle {
  readonly zip = new yazl.ZipFile();
  private used = new Set<string>();
  private assets = new Map<string, string>();

  /** A unique file name in `dir` (adds " 2", " 3"… before the extension). */
  unique(dir: string, name: string, ext: string) {
    let p = path.posix.join(dir, `${name}${ext}`);
    for (let i = 2; this.used.has(p.toLowerCase()); i++) p = path.posix.join(dir, `${name} ${i}${ext}`);
    this.used.add(p.toLowerCase());
    return p;
  }

  text(p: string, s: string) {
    this.zip.addBuffer(Buffer.from(s, "utf8"), p);
  }

  /** Copies an uploaded file into assets/ once. Returns its path in the zip, or null. */
  upload(url: string): string | null {
    const m = /^\/uploads\/([\w.-]+)$/.exec(url);
    if (!m) return null;
    const file = path.join(UPLOAD_DIR, m[1]);
    if (!fs.existsSync(file)) return null;
    let p = this.assets.get(url);
    if (!p) {
      p = `assets/${m[1]}`;
      this.assets.set(url, p);
      this.zip.addFile(file, p, { compress: !/\.(png|jpe?g|gif|webp|pdf|pptx?|zip)$/i.test(file) });
    }
    return p;
  }

  /** Adds generated bytes under assets/ once per key. */
  buffer(key: string, name: string, data: () => Buffer | null): string | null {
    let p = this.assets.get(key);
    if (p) return p;
    const buf = data();
    if (!buf) return null;
    p = `assets/${name}`;
    this.assets.set(key, p);
    this.zip.addBuffer(buf, p);
    return p;
  }
}

const safeName = (s: string, fallback = "Untitled") =>
  s
    .replace(/[\u0000-\u001f<>:"/\\|?*]+/g, " ")
    .replace(/\s+/g, " ")
    .replace(/[. ]+$/, "")
    .trim()
    .slice(0, 80) || fallback;

/** Link from one file in the zip to another (relative, URL-encoded). */
const rel = (from: string, to: string) => encodeURI(path.posix.relative(path.posix.dirname(from), to));

// ── Markdown ─────────────────────────────────────────────────────────────

type Ctx = {
  bundle: Bundle;
  /** Path of the file being written, inside the zip. */
  file: string;
  /** Exported material id → its file, for "@" links. */
  files: Map<string, string>;
  /** Region id → number (counting through the whole material). */
  regionNums: Map<string, number>;
  headingNums: Map<string, string>;
  /** Number of the next region to list under an image. */
  nextRegion: number;
};

const escapeMd = (s: string) => s.replace(/([\\`*_[\]<>$])/g, "\\$1");

function asset(ctx: Ctx, url: string): string {
  const p = ctx.bundle.upload(url);
  return p ? rel(ctx.file, p) : url;
}

function inlineMd(content: unknown, ctx: Ctx): string {
  if (typeof content === "string") return escapeMd(content);
  if (!Array.isArray(content)) return escapeMd(contentText(content));
  let out = "";
  let openRegion: string | null = null;
  const closeRegion = () => {
    const n = openRegion ? ctx.regionNums.get(openRegion) : undefined;
    if (n) out += `<sup>[${n}]</sup>`;
    openRegion = null;
  };
  for (const raw of content) {
    const item = (raw ?? {}) as Record<string, unknown>;
    const styles = (item.styles ?? {}) as Record<string, unknown>;
    const region = typeof styles.annotation === "string" && styles.annotation ? styles.annotation : null;
    if (region !== openRegion) closeRegion();
    if (item.type === "text") {
      out += styled(String(item.text ?? ""), styles);
      openRegion = region;
    } else if (item.type === "link") {
      out += `[${inlineMd(item.content, ctx)}](${String(item.href ?? "")})`;
    } else if (item.type === "math") {
      const latex = String((item.props as { latex?: string })?.latex ?? "").trim();
      if (latex) out += `$${latex}$`;
    } else if (item.type === "mention") {
      const p = (item.props ?? {}) as Partial<MentionProps>;
      const target = p.targetId ? ctx.files.get(p.targetId) : undefined;
      const label = escapeMd(`@${p.label || "link"}`);
      out += target ? `[${label}](${rel(ctx.file, target)})` : `**${label}**`;
    } else {
      out += escapeMd(contentText(item));
    }
  }
  closeRegion();
  return out;
}

function styled(text: string, styles: Record<string, unknown>): string {
  if (!text) return "";
  // Markers can't sit next to the spaces they wrap, so keep those outside.
  const [, lead, core, trail] = /^(\s*)([\s\S]*?)(\s*)$/.exec(text) as RegExpExecArray;
  if (!core) return text;
  let s: string;
  if (styles.code) {
    const ticks = core.includes("`") ? "``" : "`";
    s = `${ticks}${core}${ticks}`;
  } else {
    s = escapeMd(core);
    if (styles.strike) s = `~~${s}~~`;
    if (styles.italic) s = `_${s}_`;
    if (styles.bold) s = `**${s}**`;
    if (styles.underline) s = `<u>${s}</u>`;
  }
  return (lead + s + trail).replace(/\n/g, "  \n");
}

const ALERT: Record<string, string> = { note: "NOTE", tip: "TIP", warning: "WARNING", exam: "IMPORTANT" };

function fence(code: string, lang = "") {
  const longest = Math.max(2, ...(code.match(/`+/g) ?? []).map((m) => m.length));
  const f = "`".repeat(longest + 1);
  return `${f}${lang}\n${code.replace(/\n$/, "")}\n${f}`;
}

const indentLines = (s: string, prefix: string, first = prefix) =>
  s
    .split("\n")
    .map((l, i) => (i === 0 ? first : l ? prefix : prefix.trimEnd()) + l)
    .join("\n");

function blocksMd(blocks: LooseBlock[], ctx: Ctx): string {
  const parts: string[] = [];
  let listNo = 0;
  for (const b of blocks) {
    listNo = b.type === "numberedListItem" ? listNo + 1 : 0;
    let md = blockMd(b, ctx, listNo);
    if (b.children?.length) {
      const kids = blocksMd(b.children, ctx);
      const pad = b.type === "numberedListItem" ? " ".repeat(`${listNo}. `.length) : "  ";
      md += `\n\n${indentLines(kids, pad)}`;
    }
    parts.push(md);
  }
  // List items stay together; everything else is separated by a blank line.
  let out = "";
  blocks.forEach((b, i) => {
    if (i > 0) {
      const tight = isListItem(b) && isListItem(blocks[i - 1]) && !blocks[i - 1].children?.length;
      out += tight ? "\n" : "\n\n";
    }
    out += parts[i];
  });
  return out;
}

const isListItem = (b: LooseBlock) => /^(bulletListItem|numberedListItem|checkListItem|toggleListItem)$/.test(b.type);

function blockMd(b: LooseBlock, ctx: Ctx, listNo: number): string {
  const p = (b.props ?? {}) as Record<string, unknown>;
  const text = () => inlineMd(b.content, ctx);
  switch (b.type) {
    case "heading": {
      const level = Number(p.level ?? 1);
      const num = ctx.headingNums.get(b.id);
      return `${"#".repeat(Math.min(6, level + 1))} ${num ? `${num} ` : ""}${text()}`;
    }
    case "bulletListItem":
    case "toggleListItem":
      return `- ${text()}`;
    case "numberedListItem":
      return `${listNo}. ${text()}`;
    case "checkListItem":
      return `- [${p.checked ? "x" : " "}] ${text()}`;
    case "quote":
      return indentLines(text(), "> ");
    case "codeBlock":
      return fence(contentText(b.content), String(p.language ?? "").replace(/^text$/, ""));
    case "divider":
      return "---";
    case "callout":
      return `> [!${ALERT[String(p.tone)] ?? "NOTE"}]\n${indentLines(text(), "> ")}`;
    case MATH_BLOCK:
      return `$$\n${String(p.latex ?? "").trim()}\n$$`;
    case "table":
      return tableMd(b.content, ctx);
    case ANNOTATED_IMAGE: {
      const name = String(p.name ?? "") || "image";
      const lines = [`![${escapeMd(name)}](${asset(ctx, String(p.url ?? ""))})`];
      const comments = parseAnnotations(p.annotations).map((a) => `${ctx.nextRegion++}. ${escapeMd(a.comment || "(no comment)")}`);
      if (comments.length) lines.push("", ...comments);
      return lines.join("\n");
    }
    case DRAWING: {
      const id = String(p.drawingId ?? "");
      const d = id ? repo.getDrawingSummary(id) : null;
      if (!d) return "_(drawing)_";
      const file = ctx.bundle.buffer(`drawing:${id}`, `drawing-${id}.svg`, () => {
        const svg = repo.getDrawingPreview(id)?.svg;
        return svg ? Buffer.from(svg, "utf8") : null;
      });
      return file ? `![${escapeMd(d.title)}](${rel(ctx.file, file)})` : `_Drawing: ${escapeMd(d.title)}_`;
    }
    case "image":
    case "video":
    case "audio":
    case "file": {
      const url = String(p.url ?? "");
      const name = escapeMd(String(p.name || p.caption || "file"));
      if (!url) return "";
      return b.type === "image" ? `![${name}](${asset(ctx, url)})` : `[${name}](${asset(ctx, url)})`;
    }
    default:
      return text();
  }
}

function tableMd(content: unknown, ctx: Ctx): string {
  const rows = ((content as { rows?: { cells: unknown[] }[] })?.rows ?? []).map((r) =>
    r.cells.map((c) => {
      const inline = (c as { type?: string; content?: unknown })?.type === "tableCell" ? (c as { content: unknown }).content : c;
      return inlineMd(inline, ctx).replace(/\|/g, "\\|").replace(/ {2}\n/g, "<br>");
    }),
  );
  if (!rows.length) return "";
  const width = Math.max(...rows.map((r) => r.length));
  const line = (cells: string[]) => `| ${Array.from({ length: width }, (_, i) => cells[i] ?? "").join(" | ")} |`;
  return [line(rows[0]), line(Array(width).fill("---")), ...rows.slice(1).map(line)].join("\n");
}

function docMd(m: Material, ctx: Ctx): string {
  const blocks = Array.isArray(m.content) ? (m.content as LooseBlock[]) : [];
  let n = 0;
  walkBlocks(blocks, (b) => {
    if (b.type === ANNOTATED_IMAGE) parseAnnotations(b.props?.annotations).forEach((a) => ctx.regionNums.set(a.id, ++n));
  });
  for (const o of buildOutline(blocks)) ctx.headingNums.set(o.id, o.num);
  return `# ${escapeMd(m.title || "Untitled")}\n\n${blocksMd(blocks, ctx)}\n`;
}

function imagePageMd(m: Material, ctx: Ctx): string {
  const page = asImagePage(m.content);
  const lines = [`# ${escapeMd(m.title || "Untitled")}`, ""];
  if (page.url) lines.push(`![${escapeMd(page.name || "image")}](${asset(ctx, page.url)})`, "");
  page.annotations.forEach((a, i) => lines.push(`${i + 1}. ${escapeMd(a.comment || "(no comment)")}`));
  return `${lines.join("\n").trimEnd()}\n`;
}

const ANSI = /\u001b\[[0-9;]*[A-Za-z]/g;
const joinText = (v: string | string[] | undefined) => (Array.isArray(v) ? v.join("") : (v ?? ""));

function notebookMd(m: Material, nb: NotebookContent, ctx: Ctx): string {
  const out = [`# ${escapeMd(m.title || "Untitled")}`];
  nb.cells.forEach((cell, ci) => {
    if (cell.cell_type !== "code") return void out.push(cell.cell_type === "raw" ? fence(cell.source) : cell.source);
    out.push(fence(cell.source, "python"));
    cell.outputs.forEach((o, oi) => {
      if (o.output_type === "stream") return void out.push(fence(joinText(o.text).replace(ANSI, "")));
      if (o.output_type === "error") {
        return void out.push(fence(o.traceback.join("\n").replace(ANSI, "") || `${o.ename}: ${o.evalue}`));
      }
      const data = o.data as MimeBundle;
      const key = `nb:${m.id}:${ci}:${oi}`;
      if (data["image/png"] || data["image/jpeg"]) {
        const png = !!data["image/png"];
        const b64 = joinText(data[png ? "image/png" : "image/jpeg"]).replace(/\s/g, "");
        const file = ctx.bundle.buffer(key, `${m.id}-${ci}-${oi}.${png ? "png" : "jpg"}`, () => Buffer.from(b64, "base64"));
        if (file) out.push(`![output](${rel(ctx.file, file)})`);
      } else if (data["image/svg+xml"]) {
        const file = ctx.bundle.buffer(key, `${m.id}-${ci}-${oi}.svg`, () => Buffer.from(joinText(data["image/svg+xml"]), "utf8"));
        if (file) out.push(`![output](${rel(ctx.file, file)})`);
      } else if (data["text/markdown"]) {
        out.push(joinText(data["text/markdown"]));
      } else if (data["text/latex"]) {
        out.push(joinText(data["text/latex"]));
      } else if (data["text/plain"]) {
        out.push(fence(joinText(data["text/plain"]).replace(ANSI, "")));
      }
    });
  });
  return `${out.join("\n\n")}\n`;
}

const ipynb = (nb: NotebookContent) => {
  const lines = (s: string) => (s ? s.split(/(?<=\n)/) : []);
  return JSON.stringify(
    {
      ...nb,
      cells: nb.cells.map((c) => ({
        ...c,
        source: lines(c.source),
        ...(c.cell_type === "code"
          ? { outputs: c.outputs.map((o) => (o.output_type === "stream" ? { ...o, text: lines(joinText(o.text)) } : o)) }
          : {}),
      })),
    },
    null,
    1,
  );
};

// ── Course / material export ─────────────────────────────────────────────

type Plan = { summary: MaterialSummary; file: string; children?: Plan[] };

const n2 = (i: number) => String(i + 1).padStart(2, "0");

/** Decides every file name first, so "@" links between them can be written. */
function plan(bundle: Bundle, items: MaterialSummary[], all: MaterialSummary[], dir: string, files: Map<string, string>): Plan[] {
  return items.map((s, i) => {
    const base = `${n2(i)} ${safeName(s.title)}`;
    if (s.kind === "folder") {
      const folderDir = bundle.unique(dir, base, "");
      const file = path.posix.join(folderDir, "README.md");
      files.set(s.id, file);
      const kids = all.filter((m) => m.parentId === s.id).sort((a, b) => a.position - b.position);
      return { summary: s, file, children: plan(bundle, kids, all, folderDir, files) };
    }
    const file = bundle.unique(dir, base, ".md");
    files.set(s.id, file);
    return { summary: s, file };
  });
}

function writePlans(bundle: Bundle, plans: Plan[], files: Map<string, string>) {
  for (const p of plans) {
    const m = repo.getMaterial(p.summary.id);
    if (!m) continue;
    const ctx: Ctx = { bundle, file: p.file, files, regionNums: new Map(), headingNums: new Map(), nextRegion: 1 };
    if (m.kind === "folder") {
      const src = asFolder(m.content).source;
      const lines = [`# ${escapeMd(m.title || "Untitled")}`, ""];
      if (src) {
        const orig = bundle.upload(src.url);
        if (orig) lines.push(`Imported from [${escapeMd(src.name)}](${rel(p.file, orig)}).`, "");
      }
      for (const c of p.children ?? []) lines.push(`- [${escapeMd(c.summary.title || "Untitled")}](${rel(p.file, c.file)})`);
      bundle.text(p.file, `${lines.join("\n").trimEnd()}\n`);
      writePlans(bundle, p.children ?? [], files);
    } else if (m.kind === "image") {
      bundle.text(p.file, imagePageMd(m, ctx));
    } else if (m.kind === "notebook") {
      const nb = asNotebook(m.content);
      bundle.text(p.file, notebookMd(m, nb, ctx));
      bundle.text(p.file.replace(/\.md$/, ".ipynb"), ipynb(nb));
    } else {
      bundle.text(p.file, docMd(m, ctx));
    }
  }
}

export type ZipStream = { name: string; stream: NodeJS.ReadableStream; cleanup?: () => void };

/** A course as Markdown: one file per material, folders as folders, images in assets/. */
export function exportCourse(courseId: string): ZipStream | null {
  const course = repo.getCourse(courseId);
  if (!course) return null;
  const bundle = new Bundle();
  const files = new Map<string, string>();
  const top = course.materials.filter((m) => !m.parentId);
  const plans = plan(bundle, top, course.materials, "", files);
  const title = [course.code, course.name].filter(Boolean).join(" · ") || "Course";
  bundle.text(
    "README.md",
    [`# ${escapeMd(title)}`, "", ...plans.map((p) => `- [${escapeMd(p.summary.title || "Untitled")}](${encodeURI(p.file)})`), ""].join(
      "\n",
    ),
  );
  writePlans(bundle, plans, files);
  bundle.zip.end();
  return { name: `${safeName(title, "Course")} (Markdown).zip`, stream: bundle.zip.outputStream };
}

/** One material (a folder with its pages) as Markdown. */
export function exportMaterial(materialId: string): ZipStream | null {
  const m = repo.getMaterial(materialId);
  const course = m && repo.getCourse(m.courseId);
  if (!m || !course) return null;
  const summary = course.materials.find((s) => s.id === m.id)!;
  const bundle = new Bundle();
  const files = new Map<string, string>();
  const plans = plan(bundle, [summary], course.materials, "", files);
  writePlans(bundle, plans, files);
  bundle.zip.end();
  return { name: `${safeName(m.title)} (Markdown).zip`, stream: bundle.zip.outputStream };
}

// ── Everything ───────────────────────────────────────────────────────────

/** The whole data folder: a snapshot of the database plus uploads and notebook folders. */
export function exportAll(): ZipStream {
  const tmp = path.join(os.tmpdir(), `gloss-export-${process.pid}-${Date.now()}.db`);
  writeSnapshot(tmp);
  const zip = new yazl.ZipFile();
  zip.addFile(tmp, "data/study.db");
  const walk = (dir: string, rel: string) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, e.name);
      const r = rel ? `${rel}/${e.name}` : e.name;
      if (!rel && (e.name === "backups" || e.name.startsWith("study.db"))) continue;
      if (e.isDirectory()) walk(abs, r);
      else if (e.isFile()) zip.addFile(abs, `data/${r}`, { compress: !/\.(png|jpe?g|gif|webp|pdf|pptx?|zip|gz)$/i.test(e.name) });
    }
  };
  walk(DATA_DIR, "");
  zip.end();
  const d = new Date();
  const day = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  return { name: `Gloss data ${day}.zip`, stream: zip.outputStream, cleanup: () => fs.rm(tmp, { force: true }, () => undefined) };
}
